# typed: false
# frozen_string_literal: true

# This file is generated by shyim/riff. Do not edit it in the tap.
class PhpRiff < Formula
  desc "Fast, standalone Composer-compatible package manager"
  homepage "https://github.com/shyim/riff"
  version "0.0.6"
  license "MIT"

  depends_on "php"

  conflicts_with "riff", because: "both install a riff executable"

  on_macos do
    on_arm do
      url "https://github.com/shyim/riff/releases/download/v0.0.6/riff-v0.0.6-aarch64-apple-darwin.tar.gz"
      sha256 "5c72969fa9e487181f97c10dc427f0d8b8ed0655a92d331acee08073d7658cb5"
    end

    on_intel do
      url "https://github.com/shyim/riff/releases/download/v0.0.6/riff-v0.0.6-x86_64-apple-darwin.tar.gz"
      sha256 "f983545b896eee3182a19f8908a7f0fec4674cf2242a7866b50ad06601f1986b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shyim/riff/releases/download/v0.0.6/riff-v0.0.6-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "111ec501def6ef2203ca6ff920f22c34fca95553a33d511b0e52534868f533a5"
    end

    on_intel do
      url "https://github.com/shyim/riff/releases/download/v0.0.6/riff-v0.0.6-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "cf4ef60763cce9d5455f31244b077cd288e5b63081e5cd42bfdde10171536b5e"
    end
  end

  def install
    bin.install "riff"
    generate_completions_from_executable(bin/"riff", "completion")
  end

  test do
    (testpath/"composer.json").write <<~JSON
      {
        "name": "homebrew/riff-test",
        "require": {}
      }
    JSON

    system bin/"riff", "install", "--no-audit", "--no-interaction", "--no-plugins", "--no-scripts"
    assert_path_exists testpath/"composer.lock"
  end
end
