# typed: false
# frozen_string_literal: true

# This file is generated by shyim/riff. Do not edit it in the tap.
class PhpRiff < Formula
  desc "Fast, standalone Composer-compatible package manager"
  homepage "https://github.com/shyim/riff"
  version "0.0.5"
  license "MIT"

  depends_on "php"

  conflicts_with "riff", because: "both install a riff executable"

  on_macos do
    on_arm do
      url "https://github.com/shyim/riff/releases/download/v0.0.5/riff-v0.0.5-aarch64-apple-darwin.tar.gz"
      sha256 "27ca6c0ddf626103a4b2349b11585983d690534a8b8c86629b16196f0cb27332"
    end

    on_intel do
      url "https://github.com/shyim/riff/releases/download/v0.0.5/riff-v0.0.5-x86_64-apple-darwin.tar.gz"
      sha256 "a0b50c73207255e4b8e95aacdefb7c2357023d2c8c92222408c479a04f5df397"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shyim/riff/releases/download/v0.0.5/riff-v0.0.5-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3072447a06698457e4ec43c0d2a4ec5c36f5f8586ad175f96d77d599fd604ff2"
    end

    on_intel do
      url "https://github.com/shyim/riff/releases/download/v0.0.5/riff-v0.0.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f0457c1a7e506b38b136a59be6cb00f4bea66127b63ba6d9c011178b03e71956"
    end
  end

  def install
    bin.install "riff"
    generate_completions_from_executable(bin/"riff", "completion")
  end

  test do
    (testpath/"composer.json").write <<~JSON
      {
        "name": "homebrew/riff-test",
        "require": {}
      }
    JSON

    system bin/"riff", "install", "--no-audit", "--no-interaction", "--no-plugins", "--no-scripts"
    assert_path_exists testpath/"composer.lock"
  end
end
