# typed: false
# frozen_string_literal: true

# This file is generated by shyim/riff. Do not edit it in the tap.
class PhpRiff < Formula
  desc "Fast, standalone Composer-compatible package manager"
  homepage "https://github.com/shyim/riff"
  version "0.0.7"
  license "MIT"

  depends_on "php"

  conflicts_with "riff", because: "both install a riff executable"

  on_macos do
    on_arm do
      url "https://github.com/shyim/riff/releases/download/v0.0.7/riff-v0.0.7-aarch64-apple-darwin.tar.gz"
      sha256 "f2bba1359005b5dfc75b5299f22bda78e7f03409c2edb93d829440deb50dfcd9"
    end

    on_intel do
      url "https://github.com/shyim/riff/releases/download/v0.0.7/riff-v0.0.7-x86_64-apple-darwin.tar.gz"
      sha256 "845439da6b0aa48cd274dd2baccc3d587ce6ccfce1dc1eebb599fd139f0a7c32"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shyim/riff/releases/download/v0.0.7/riff-v0.0.7-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f30fbb890e9e34555ad190dccd35e3e459a4e09431e57e5cc3bbdba872fafa44"
    end

    on_intel do
      url "https://github.com/shyim/riff/releases/download/v0.0.7/riff-v0.0.7-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c9ff6410a9c1650c1547140f59bc51fffa8defab01919e6cebf1b7b3aaeef17f"
    end
  end

  def install
    bin.install "riff"
    generate_completions_from_executable(bin/"riff", "completion")
  end

  test do
    (testpath/"composer.json").write <<~JSON
      {
        "name": "homebrew/riff-test",
        "require": {}
      }
    JSON

    system bin/"riff", "install", "--no-audit", "--no-interaction", "--no-plugins", "--no-scripts"
    assert_path_exists testpath/"composer.lock"
  end
end
