# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tanjun < Formula
  desc "Simple Dockerized Deployment"
  homepage "https://shyim.me"
  version "0.0.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shyim/tanjun/releases/download/0.0.4/tanjun_Darwin_x86_64.tar.gz"
      sha256 "5048090ab6386d64bc326d90c839bafd5a22f92b6f87731ec96e212a801770ba"

      def install
        bin.install "tanjun"
        bash_completion.install "completions/tanjun.bash" => "_tanjun"
        zsh_completion.install "completions/tanjun.zsh" => "_tanjun"
        fish_completion.install "completions/tanjun.fish"
      end
    end
    on_arm do
      url "https://github.com/shyim/tanjun/releases/download/0.0.4/tanjun_Darwin_arm64.tar.gz"
      sha256 "6f112a5000bcf6ba4bb48a32cb7da54403e24f96fd009f7f4105717d05f394cb"

      def install
        bin.install "tanjun"
        bash_completion.install "completions/tanjun.bash" => "_tanjun"
        zsh_completion.install "completions/tanjun.zsh" => "_tanjun"
        fish_completion.install "completions/tanjun.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shyim/tanjun/releases/download/0.0.4/tanjun_Linux_x86_64.tar.gz"
        sha256 "fbd5ba21c99e00ce35f3f4c5f3695bffcf16c11aee7b02daa6fa76dc7405d5df"

        def install
          bin.install "tanjun"
          bash_completion.install "completions/tanjun.bash" => "_tanjun"
          zsh_completion.install "completions/tanjun.zsh" => "_tanjun"
          fish_completion.install "completions/tanjun.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shyim/tanjun/releases/download/0.0.4/tanjun_Linux_arm64.tar.gz"
        sha256 "f89d0fe08a05edeeb77efc9e4bcf7e5fff57ade12f8d1f1b25c5c013845a463a"

        def install
          bin.install "tanjun"
          bash_completion.install "completions/tanjun.bash" => "_tanjun"
          zsh_completion.install "completions/tanjun.zsh" => "_tanjun"
          fish_completion.install "completions/tanjun.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/tanjun --version"
  end
end
