# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tanjun < Formula
  desc "Simple Dockerized Deployment"
  homepage "https://shyim.me"
  version "0.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shyim/tanjun/releases/download/0.0.3/tanjun_Darwin_x86_64.tar.gz"
      sha256 "a4ea6240eda660a885987e6de4b9c4e672ff9b996bb49a4a449d34930e470746"

      def install
        bin.install "tanjun"
        bash_completion.install "completions/tanjun.bash" => "_tanjun"
        zsh_completion.install "completions/tanjun.zsh" => "_tanjun"
        fish_completion.install "completions/tanjun.fish"
      end
    end
    on_arm do
      url "https://github.com/shyim/tanjun/releases/download/0.0.3/tanjun_Darwin_arm64.tar.gz"
      sha256 "bf5f9d31d18b69c4379e589b8b675d4283a4dc35b966c5966e4160583e3a8f34"

      def install
        bin.install "tanjun"
        bash_completion.install "completions/tanjun.bash" => "_tanjun"
        zsh_completion.install "completions/tanjun.zsh" => "_tanjun"
        fish_completion.install "completions/tanjun.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shyim/tanjun/releases/download/0.0.3/tanjun_Linux_x86_64.tar.gz"
        sha256 "c5383db483844bbc1b4ca1dc868b624d125610153e391cca8c75961ae6da0f89"

        def install
          bin.install "tanjun"
          bash_completion.install "completions/tanjun.bash" => "_tanjun"
          zsh_completion.install "completions/tanjun.zsh" => "_tanjun"
          fish_completion.install "completions/tanjun.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shyim/tanjun/releases/download/0.0.3/tanjun_Linux_arm64.tar.gz"
        sha256 "e9e8b54e80b58e72d2f46275d329aacbf366060c353c84db65f84a13ea96cc9f"

        def install
          bin.install "tanjun"
          bash_completion.install "completions/tanjun.bash" => "_tanjun"
          zsh_completion.install "completions/tanjun.zsh" => "_tanjun"
          fish_completion.install "completions/tanjun.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/tanjun --version"
  end
end
